### ISSUE TITLE
`Unknown function: nvimhs#start`

### ISSUE THREAD

**Issue by Zelatrix** [isovector/cornelis#100]
I have just tried to install this on Vim, and I have also made sure that `stack` is installed and in my `PATH`. When I try and open a file like `a.agda` I am met with some error messages

```
Error detected while processing /home/callum/.vim/plugged/cornelis/ftplugin/agda.vim
Unknown function: nvimhs#start
Unknown function: textobj#user#plugin
```

I have also tried to install the plugin on Neovim in case the error is because it doesn't work on Vim and only on Neovim, but I am met with the same error. Could you help me with installing this plugin?

**Comment by isovector** [comment]
Looks like you forgot to add the `nvimhs` and `vim-textobj-user` plugins as suggested here: https://github.com/isovector/cornelis#installation

If you did do that, make sure your [vim-plug](https://github.com/junegunn/vim-plug) is installed properly, and then try running `:PlugInstall`.

**Comment by Zelatrix** [comment]
I have done that and also run `:PlugInstall` and those specific errors go away, but then I get some different errors instead:

```
Error detected while processing nvimhs#start
Unknown function: remote#host#Register
Unknown function: remote#host#Require
```

**Comment by isovector** [comment]
I think now you're running `vim` rather than `nvim`.

**Comment by Zelatrix** [comment]
I am, yes. Does this plugin not work on vanilla Vim?

**Comment by isovector** [comment]
I'm going to close this, but feel free to reopen if you run into more problems!
