### ISSUE TITLE
Provide snippets for unicode selection

### ISSUE THREAD

**Issue by 4e554c4c** [isovector/cornelis#108]
it would be nice to have a plugin-independent way to get insert-mode bindings for agda. For example, I use https://github.com/L3MON4D3/LuaSnip which allows for importing vscode-like or SnipMate-like shortcuts, or can be configured in lua.

**Comment by isovector** [comment]
What do you have in mind? It's not immediately clear to me how insert-mode bindings would tie into a snippet. Perhaps `cornelis#bind_input` could invoke a callback for being tied into any other system?

**Comment by 4e554c4c** [comment]
snippets don't need to contain additional cursor locations, or even "expand" text. They can just be mappings like `\n` to `ℕ`
to see an example, here are my snippets in the [vscode style](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax) for lean: https://git.sr.ht/~pounce/dotfiles/tree/main/item/private_dot_config/nvim/snippets

the benefit of non defining how input-mode text is expanded in cornelis is that users would be able to integrate it with their own completion engine, such as `nvim-cmp`.

**Comment by isovector** [comment]
Sorry for being dense, but I don't know what a resolution to this issue would look like.  Could you walk me through, in excruciating detail, what you'd like cornelis to do (or not do)?

**Comment by 4e554c4c** [comment]
Yes, sorry.
Being able to hook `cornelis#bind_input` would be fine, I think.

**Comment by isovector** [comment]
Implemented in 10984fbc48fc3a8825e835e42eeef21c787a60a2.
