### ISSUE TITLE
`CornelisUnsolvedMeta` highlight does not appear some of the time

### ISSUE THREAD

**Issue by 4e554c4c** [isovector/cornelis#125]
screenshot:

![image](https://github.com/isovector/cornelis/assets/4743113/b8309797-7b9b-40a5-af1f-13054a1af10b)

As indicated in the screenshot, while the hole on line 10 always shows as highlighted, the unsolved meta on line 8 does not appear highlighted. This does not always occur, and appears to be due to a race condition involving which highlights are applied to the term in what order.

`:Inspect` on the unsolved meta yields
```
Extmarks                                             
  - CornelisSymbol links to Normal cornelis
  - CornelisUnsolvedMeta links to DiagnosticWarn cornelis
  - CornelisSymbol links to Normal cornelis
```

Thus, the two `Normal` highlight groups on the term are taking priority over the `DiagnosticWarn` highlight.

Also, as a nit I see no reason that `CornelisHole` should be linked to `Todo` and `CornelisUnsolvedMeta` should be linked to `DiagnosticWarn`, when both are a hole in the program (and usually show up the same color in agda-mode).

**Comment by isovector** [comment]
i'd love a PR for this!

**Comment by 4e554c4c** [comment]
this doesn't seem like the easiest problem to solve, since vim highlight groups can't be given priority over each other.
We would need some way to make sure that at most one highlight group is applied to each portion of text

**Comment by 4e554c4c** [comment]
There appear to be different ways to set priority of highlights. See `vim.highlight.range()` in the lua API, which takes a highlight group and priority. I am also optimistic about `ui-hlstate`, which includes a very low level API for highlighting and includes priority.

**Comment by 4e554c4c** [comment]
I'm also not sure whether we could use semantic tokens (since Cornelis isn't technically an LSP) but these have the same extmark API that we are currently using, and allow setting a priority. This is what the Lean plugin does, so it might be a good bet. (see `:h vim.lsp.semantic_tokens.highlight_token()`)
