### ISSUE TITLE
How to check type of term under cursor

### ISSUE THREAD

**Issue by langfield** [isovector/cornelis#127]
How do you check the type of the highlighted term using cornelis?

**Comment by isovector** [comment]
I don't think you can. Does this functionality exist in emacs?

**Comment by langfield** [comment]
Oh, too bad! Not sure about emacs. Is this a limitation imposed by the compiler?

**Comment by isovector** [comment]
Cornelis is just an interface between vim and the compiler. I'm happy to implement any functionality that is missing in parity with emacs, but i can't work miracles (unfortunately!)

A good temporary workaround here is to replace the term you care about with a question mark and reload.

**Comment by langfield** [comment]
I see, I see. Tell me, is it possible to get it to auto-load on each edit, similar to how HLS works?

**Comment by googleson78** [comment]
> How do you check the type of the highlighted term using cornelis?
> I don't think you can. Does this functionality exist in emacs?

I think it doesn't exist directly, but there is ["Infer (deduce) type](https://agda.readthedocs.io/en/latest/tools/emacs-mode.html#global-commands), which should be relatively easy to wire up to work with the item under the cursor. Not sure it's a good idea in general though - putting stuff in a hole and then looking at types results in a better UX from my experience using agda in emacs.

> I see, I see. Tell me, is it possible to get it to auto-load on each edit, similar to how HLS works?

This should be trivially doable with an `autocmd`, e.g. something like
```viml
autocmd TextChangedI ?* <call cornelis reload>
```

**Comment by langfield** [comment]
Seems like this has been answered satisfactorily! Thanks @googleson78 @isovector! 💯
