### ISSUE TITLE
Refine with argument

### ISSUE THREAD

**Issue by lehmacdj** [isovector/cornelis#49]
First of all, this is quite a fantastic plugin in my use so far, enjoying using it over emacs with evil mode so far.

In agda mode in emacs I can refine with a function argument. For example, given:
```agda
isEven : ℕ → Type
isEven zero = ⊤
isEven (suc n) = {! isEven !}
```

Refining the goal produces:
```agda
isEven : ℕ → Type
isEven zero = ⊤
isEven (suc n) = isEven {!  !}
```

This is maybe not the best example, but when using a function that has many arguments it also succeeds and produces subgoals for each of the arguments and I find this functionality pretty useful.

**Comment by isovector** [comment]
Thanks for the report! Should be fixed by 010175b23f46a782ae66884195ce0fcb7347d7b6.

**Comment by isovector** [comment]
This is a pretty good argument for automatically replacing `?` holes with `{! !}`s. Do you think that should be the default behavior in cornelis?

**Comment by googleson78** [comment]
Yes, I think it's the default behaviour in the spacemacs layer (on file reload). It's very convenient to me.

**Comment by isovector** [comment]
622af1460f37fe874659a84e33933fd1aab68e4a is a better fix for the original issue; this one now dynamically looks at the contents of the `{! !}`, meaning you don't need to reload before doing the refine.

**Comment by isovector** [comment]
and 85c7dec905ca1dd9088418bb171f2a3ef53c63ad should replace `?` with `{! !}` which turns out to be way harder than it sounds :)
