### ISSUE TITLE
Weird syntax highlighting

### ISSUE THREAD

**Issue by masaeedu** [isovector/cornelis#55]
Hi there. I've been some weird syntax highlighting that seems to come and go, e.g.

![image](https://user-images.githubusercontent.com/3674056/160272525-b6325dd7-4980-412b-9240-a5beafbba3b8.png)

I'm vaguely aware that this might be an known issue, but I didn't see an issue on the tracker for it.

**Comment by isovector** [comment]
Have a reproduction? My guess is that running `:CornelisRestart` and then `:CornelisLoad` will fix it.

**Comment by isovector** [comment]
Closing due to no repro
