### ISSUE TITLE
Restrict height of the view with the goals

### ISSUE THREAD

**Issue by Eloitor** [isovector/cornelis#63]
When running `:CornelisLoad` on a file with a lot of goals, like https://github.com/martinescardo/HoTTEST-Summer-School/blob/main/Agda/Exercises/01-Exercises.lagda.md the view with the goals fills my entire window. Is it possible to restrict it to be smaller? How can this be done?

Edit: I just saw it is related to #60

**Comment by isovector** [comment]
Fixed in 37c04e36dd35dbca13bdada79276470bba6adddf
