### ISSUE TITLE
Do syntax highlighting for cubical terms in infowin

### ISSUE THREAD

**Issue by isovector** [isovector/cornelis#68]
Right now Agda just dumps out some strings to show. It's fine but they're structured and easy enough to give some coloring to

**Comment by 4e554c4c** [comment]
https://github.com/Julian/lean.nvim does this by setting the infowin to a special filetype (which I added in #107) and then provides a syntax file for it: https://github.com/Julian/lean.nvim/blob/main/syntax/leaninfo.vim
we could probably do this too

**Comment by isovector** [comment]
This is probably a better technique than the current pretty-printer thing. I'd adore a similar PR on this front, if you have some energy @4e554c4c .
