### ISSUE TITLE
Questionmarks are replaced by `{! !}` in non-hole positions

### ISSUE THREAD

**Issue by phijor** [isovector/cornelis#71]
Consider the following code:

```agda
data Foo : Set where
  Bar : Foo
  Baz : Foo

foo? : Foo → Set
foo? f = {! !}
```

When case-splitting on `f`, the clauses of `foo?` become

```agda
foo? : Foo → Set
foo{! !} Bar = {! !}
foo{! !} Baz = {! !}
```

**Comment by isovector** [comment]
Nice catch.

The whole `?` vs `{! !}` thing is surprisingly hard. IIRC, Agda doesn't actually inform us of new holes, and synthesizes new code with `?`s. `agda-mode` gets around this by waiting for highlighting information and replacing `Hole` highlit areas with `{! !}`.

I went down that road for a while, but it's rife with race conditions and I don't know how to do better.

A good solution here would be a patch to Agda for reporting new interaction points when returning code. An OK solution would be someone to wrap their head around why the race conditions aren't a problem in emacs.

A quick solution would be to only replace `?`s in synthesized code that match `\b?\b`. I don't know agda well enough to know if this would be sufficient, but it's an easy thing to try.

**Comment by isovector** [comment]
More for posterity than anything else, the following is an IOTCM session between `agda-mode` and `agda`. Of particular interest is the `Cmd_give` exchange, which my understanding is `agda-mode` saying "ok, you gave me this solution, and so now I am going to tell you I am filling the hole with it."

Cornelis doesn't yet do this, but it might help with the newly-synthesized interaction points.

[snoop.txt](https://github.com/isovector/cornelis/files/9331788/snoop.txt)

**Comment by isovector** [comment]
I think 42ed559 fixes this particular problem, and I'm happy to punt on the bigger issue of interaction points. Please give it a try!

**Comment by phijor** [comment]
I tried the fix, and it seems to work! I'm pretty sure this prevents most (all?) false replacements, as Agda's lexer recognises a single `?` as a hole anywhere in a source file (even in `syntax` declarations).

I do agree though that changing the interaction mode to send notifications for updated hole locations is probably the right way of fixing this. I haven't looked at Agda's source code in a while, but maybe I can also try to wrap my head around it. I'm willing to speculate the that the emacs mode is racy too, it just doesn't run into the issue by sheer luck.

PS: I'd love for people to join forces to implement a proper _Agda Language Server_...

**Comment by isovector** [comment]
I'm relatively involved on the Haskell language server, and I don't think LSP is a good fit for the stuff that `agda-mode` does, unfortunately. I'd love to be proven wrong, but it's not an area I'd like to dedicate my energy :)

Anyway, I'm closing this issue --- thanks for the report, and do let me know if you run into any other headaches!
