### ISSUE TITLE
Typo in arrow binding?

### ISSUE THREAD

**Issue by chezbgone** [isovector/cornelis#75]
I'm not sure if this is a typo or not, but this was a little unexpected, and is not consistent with [the binding in the emacs agda-mode](https://github.com/agda/agda/blob/master/src/data/emacs-mode/agda-input.el#L359).

https://github.com/isovector/cornelis/blob/ec3e07e05383e3f54cb3c0d3a922d6e0d6288a58/agda-input.vim#L17

**Comment by isovector** [comment]
Not intentional; probably something went wrong when I did some live vim macroing to turn emacs into vimscript :) A PR would be most welcome!
