### ISSUE TITLE
Minor highlighting issue

### ISSUE THREAD

**Issue by Lysxia** [isovector/cornelis#88]
I have some strange bits of highlighting sometimes, see attached (above, before "normal" highlighting kicks in; below, after that).

![Untitled](https://user-images.githubusercontent.com/2515201/199213518-939aeacd-dce8-47f6-93f5-75164bb83abc.png)

For some reason, "`Reasonin`" in `|-Reasoning` is being highlighted on its own and the color persists through reloading the file.

I can look into this later, but I opened this just in case you had a guess about what's going on.

**Comment by isovector** [comment]
Stupid question, but does it persist after running `:noh`? The fact that it's on line 1 and 3 makes me think this isn't coming from Agda. Otherwise I have no idea :)

**Comment by Lysxia** [comment]
:facepalm: That was it. Sorry for the noise :)
