### ISSUE TITLE
Utils for debugging

### ISSUE THREAD

**Issue by Lysxia** [isovector/cornelis#99]
When hacking on cornelis, I spend a lot of time looking at messages sent by Agda and nvim to reverse engineer their protocols. Right now in my PR #98 I added a `debug` function to dump arbitrary things into a file.

1. Does the nvim API have anything for logging? `notify` doesn't seem like it's supposed to receive more than a couple of lines at a time.
2. Does `debug` in #98 look good enough to keep or do you have other preferences about what the `Debug` should look like?

**Comment by isovector** [comment]
1. nvim-hs as called by cornelis dumps a file `/tmp/cornelis.log` corresponding somewhat to the messages being sent between the two. Which is helpful for debugging nvim-hs, but I don't think it generalizes to other use cases.
2. Keep it!
